const shared = {
 it:{nav:['Esperienza','Servizi','Venezia','Contatti'], eyebrow:'Luxury Experience · Venezia', title:'Venezia.\nDa una prospettiva unica.', subtitle:'Un’esperienza esclusiva tra i canali più iconici di Venezia.', discover:'Scopri l’esperienza', contact:'Contattaci', experience:'Non è semplicemente un giro in gondola.', authentic:'È Venezia vista dal suo punto di vista più autentico.', services:'Esperienze pensate per restare.', immersive:'Venezia.\nCome dovrebbe essere vissuta.', tradition:'Ogni percorso racconta una Venezia diversa.', journey:'Il tuo viaggio inizia qui.', footer:'Venezia, Italia', descriptions:['L’essenza senza tempo dei canali veneziani.','Un momento intimo, disegnato per due.','Per celebrare ciò che merita di essere ricordato.','Un itinerario creato intorno a te.']},
 en:{nav:['Experience','Services','Venice','Contact'], eyebrow:'Luxury Experience · Venice', title:'Venice.\nFrom a unique perspective.', subtitle:'An exclusive experience through Venice’s most iconic canals.', discover:'Discover the experience', contact:'Contact us', experience:'It is not simply a gondola ride.', authentic:'It is Venice, seen from its most authentic point of view.', services:'Experiences made to remain with you.', immersive:'Venice.\nAs it should be experienced.', tradition:'Every route tells a different Venice.', journey:'Your journey starts here.', footer:'Venice, Italy', descriptions:['The timeless essence of Venetian canals.','An intimate moment, designed for two.','To celebrate what deserves to be remembered.','An itinerary shaped around you.']},
 fr:{nav:['Expérience','Services','Venise','Contacts'], eyebrow:'Luxury Experience · Venise', title:'Venise.\nD’une perspective unique.', subtitle:'Une expérience exclusive au fil des canaux les plus emblématiques de Venise.', discover:'Découvrir l’expérience', contact:'Nous contacter', experience:'Ce n’est pas simplement un tour en gondole.', authentic:'C’est Venise, vue depuis son point de vue le plus authentique.', services:'Des expériences faites pour rester.', immersive:'Venise.\nComme elle devrait être vécue.', tradition:'Chaque parcours raconte une Venise différente.', journey:'Votre voyage commence ici.', footer:'Venise, Italie', descriptions:['L’essence intemporelle des canaux vénitiens.','Un moment intime, conçu pour deux.','Pour célébrer ce qui mérite d’être retenu.','Un itinéraire créé autour de vous.']},
 de:{nav:['Erlebnis','Leistungen','Venedig','Kontakt'], eyebrow:'Luxury Experience · Venedig', title:'Venedig.\nAus einer einzigartigen Perspektive.', subtitle:'Ein exklusives Erlebnis auf den berühmtesten Kanälen Venedigs.', discover:'Erlebnis entdecken', contact:'Kontakt', experience:'Es ist nicht einfach eine Gondelfahrt.', authentic:'Es ist Venedig aus seiner authentischsten Perspektive.', services:'Erlebnisse, die bleiben.', immersive:'Venedig.\nWie es erlebt werden sollte.', tradition:'Jede Route erzählt ein anderes Venedig.', journey:'Ihre Reise beginnt hier.', footer:'Venedig, Italien', descriptions:['Die zeitlose Essenz venezianischer Kanäle.','Ein intimer Moment für zwei.','Um das zu feiern, was Erinnerung verdient.','Eine Route, ganz nach Ihnen gestaltet.']},
 es:{nav:['Experiencia','Servicios','Venecia','Contacto'], eyebrow:'Luxury Experience · Venecia', title:'Venecia.\nDesde una perspectiva única.', subtitle:'Una experiencia exclusiva entre los canales más icónicos de Venecia.', discover:'Descubre la experiencia', contact:'Contáctanos', experience:'No es simplemente un paseo en góndola.', authentic:'Es Venecia desde su perspectiva más auténtica.', services:'Experiencias hechas para perdurar.', immersive:'Venecia.\nComo debe vivirse.', tradition:'Cada ruta cuenta una Venecia diferente.', journey:'Tu viaje empieza aquí.', footer:'Venecia, Italia', descriptions:['La esencia atemporal de los canales venecianos.','Un momento íntimo pensado para dos.','Para celebrar lo que merece ser recordado.','Un itinerario creado a tu medida.']},
 pt:{nav:['Experiência','Serviços','Veneza','Contacto'], eyebrow:'Luxury Experience · Veneza', title:'Veneza.\nDe uma perspetiva única.', subtitle:'Uma experiência exclusiva pelos canais mais icónicos de Veneza.', discover:'Descubra a experiência', contact:'Contacte-nos', experience:'Não é apenas um passeio de gôndola.', authentic:'É Veneza, vista do seu ponto mais autêntico.', services:'Experiências feitas para ficar.', immersive:'Veneza.\nComo deve ser vivida.', tradition:'Cada percurso conta uma Veneza diferente.', journey:'A sua viagem começa aqui.', footer:'Veneza, Itália', descriptions:['A essência intemporal dos canais venezianos.','Um momento íntimo, pensado para dois.','Para celebrar o que merece ser lembrado.','Um itinerário criado à sua volta.']}
};
const details = {
 it: { names:['Giro Classico','Esperienza Romantica','Occasioni Speciali','Esperienza Personalizzata'], routeLabel:'L’arte del percorso', routeCopy:'Ogni dettaglio è pensato: il silenzio di un piccolo canale, la luce che cambia sull’acqua, una città che si svela seguendo il proprio ritmo.', more:'Scopri di più', scroll:'Scorri' },
 en: { names:['Classic Journey','Romantic Experience','Special Occasions','Tailored Experience'], routeLabel:'The art of the route', routeCopy:'Every detail is considered: the silence of a narrow canal, the changing light on water, the city revealing itself at its own pace.', more:'Discover more', scroll:'Scroll' },
 fr: { names:['Balade Classique','Expérience Romantique','Occasions Spéciales','Expérience Sur Mesure'], routeLabel:'L’art du parcours', routeCopy:'Chaque détail est pensé : le silence d’un petit canal, la lumière changeante sur l’eau, une ville qui se dévoile à son propre rythme.', more:'En savoir plus', scroll:'Défiler' },
 de: { names:['Klassische Fahrt','Romantisches Erlebnis','Besondere Anlässe','Individuelles Erlebnis'], routeLabel:'Die Kunst der Route', routeCopy:'Jedes Detail ist bedacht: die Stille eines schmalen Kanals, das wechselnde Licht auf dem Wasser, die Stadt, die sich in ihrem eigenen Tempo zeigt.', more:'Mehr entdecken', scroll:'Scrollen' },
 es: { names:['Paseo Clásico','Experiencia Romántica','Ocasiones Especiales','Experiencia Personalizada'], routeLabel:'El arte del recorrido', routeCopy:'Cada detalle está pensado: el silencio de un pequeño canal, la luz cambiante sobre el agua, una ciudad que se revela a su propio ritmo.', more:'Descubre más', scroll:'Desliza' },
 pt: { names:['Passeio Clássico','Experiência Romântica','Ocasiões Especiais','Experiência Personalizada'], routeLabel:'A arte do percurso', routeCopy:'Cada detalhe é pensado: o silêncio de um pequeno canal, a luz que muda na água, uma cidade que se revela ao seu próprio ritmo.', more:'Descubra mais', scroll:'Deslize' },
};
for (const code of Object.keys(shared)) Object.assign(shared[code], details[code]);
export default shared;
